### ISSUE TITLE
Modificaciones 2

### ISSUE THREAD

**Issue by sjbaezb** [fbaglivo/INECO_SWM#2]
1. Reducir el número de estímulos. Envío al mail el excel con los estímulos seleccionados
2. Modificar los tiempos que tienen los sujetos para responder la pregunta. Deberían quedar así:
a) Para los conjuntos de tres palabras 4500 ms
b) Para los conjuntos de cuatro palabras 5500 ms
c) Para los conjuntos de cinco palabras 6500 ms

**Comment by fbaglivo** [comment]
Listo! Ya esta subida la V3 con las modificaciones.

**Comment by sjbaezb** [comment]
Gracias Fabri! La pruebo y te cuento
