### ISSUE TITLE
Botón para pausar

### ISSUE THREAD

**Issue by sjbaezb** [fbaglivo/INECO_SWM#3]
Agregar por favor un botón para pausar la tarea en caso de que sea necesario. La idea es que se pueda pausar y retomar sin perder datos

**Comment by fbaglivo** [comment]
Hola Sandra! Deberia poder pausarse durante la pantalla de estímulo o en
que momento|s?

**Comment by fbaglivo** [comment]
Hola Sandra, ya está agregado el feature 'Pause'. En el readme te explica como funciona, pero básicamente es apretando 'p' para pausar y 'r' para seguir.

Saludos!
